# Handle ros distro
ARG UBUNTU_DISTRO=focal
ARG ROS1_DISTRO=noetic
ARG ROS2_DISTRO=humble

FROM ubuntu:${UBUNTU_DISTRO}

ARG ROS1_DISTRO
ARG ROS2_DISTRO
ARG USER=root
ARG HOME=/home/${USER}

ENV DEBIAN_FRONTEND noninteractive
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility

# Setup locale
RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

# Create and configure a new user
ARG UID=1000
ARG GID=1000
RUN addgroup --gid ${GID} ${USER}
RUN useradd -m ${USER} && echo "${USER}:${USER}passwd" | chpasswd && adduser ${USER} sudo
RUN usermod -a -G dialout ${USER}

WORKDIR ${HOME}
RUN chown -R ${USER}:${USER} ${HOME}

# Install tools and ROS2 Humble from sources
RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN apt install -y software-properties-common curl
RUN add-apt-repository universe

RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update && apt install -y \
  python3-flake8-docstrings \
  python3-pip \
  python3-pytest-cov \
  ros-dev-tools

RUN python3 -m pip install -U \
  flake8-blind-except \
  flake8-builtins \
  flake8-class-newline \
  flake8-comprehensions \
  flake8-deprecated \
  flake8-import-order \
  flake8-quotes \
  "pytest>=5.3" \
  pytest-repeat \
  pytest-rerunfailures

RUN mkdir -p ${HOME}/ros2_${ROS2_DISTRO}/src
RUN chown -R ${USER}:${USER} ${HOME}/ros2_${ROS2_DISTRO}
WORKDIR ${HOME}/ros2_${ROS2_DISTRO}
RUN vcs import --input https://raw.githubusercontent.com/ros2/ros2/${ROS2_DISTRO}/ros2.repos src

RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN rosdep init

USER ${USER}
RUN rosdep update

USER root
RUN rosdep install -y --rosdistro ${ROS2_DISTRO} --from-paths src --ignore-src --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"
RUN colcon build --symlink-install

# Install ROS1 noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

USER root
RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN apt install -y ros-noetic-ros-base

# Install ros1 bridge
ENV ROS1_INSTALL_PATH=/opt/ros/${ROS1_DISTRO}
ENV ROS2_INSTALL_PATH=${HOME}/ros2_${ROS2_DISTRO}/install

RUN apt update --fix-missing && apt upgrade -y && apt clean
RUN mkdir -p ${HOME}/bridge_ws/src
RUN chown -R ${USER}:${USER} ${HOME}/bridge_ws

USER ${USER}
WORKDIR ${HOME}/bridge_ws/src
RUN git clone https://github.com/ros2/ros1_bridge

WORKDIR ${HOME}/bridge_ws
RUN colcon build --symlink-install --packages-skip ros1_bridge

RUN /bin/bash -c "source ${ROS1_INSTALL_PATH}/setup.bash && \
  source ${ROS2_INSTALL_PATH}/setup.bash && \
  colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure"

WORKDIR ${HOME}

CMD [ "bash" ]
